# General Jekyll Config
url: https://dmd1070.com
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock, atom.xml]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#4EA3D0'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: DMD1070

  # "Hi, I'm _______"
  name: DMD1070
  email: test@example.com
  tagline: Fundamentals of Web Design
  description: "DMD1070: Foundations of Web Design is an open source curriculum for the course offered at the University of Connecticut, Stamford."

  excerpt_separator: <!--more-->

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
